export interface ColorItem {
    name: string,
    group?: string,
    hex: string,
    rgb: string,
    cmyk?: string,
    sass?:string,
    pantone?: string,
    color_1?: string,
    color_2?: string,
    color_3: string,
    color_4?: string,
    color_5?: string,
    rgb_1?: string,
    rgb_2?: string,
    rgb_4?: string,
    rgb_5?: string,
}