name: Publish Storybook

on:
  push:
    branches:
      - storybook
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: publish
        name: Publish to Cloudflare Pages
        uses: docker://us-docker.pkg.dev/deepops/pub/github-action-cloudflare-pages:1.0
        with:
          project: alps-storybook
          directory: .storybook-build
          build: build-storybook
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_PAGES_TOKEN_DV }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_DV }}